---
# tasks file for php-Debian
# Actualizar caché de los paquetes
- name: Update cahce
  apt:
        name: '*'
        state: latest
        update_cache: true

# Instalar paquetes necesarios
- name: Install required packages
  apt:
        name:
            - php
            - php-gd
            - php-xml
            - php-mbstring
            - php-mysql
        state: latest

# Comprobar si wordpress está instalado
- name: Check wordpress.tar.gz
  stat:
          path: "/tmp/wordpress.tar.gz"
  register: tar_wordpress
          
# Descargar Archivos Wordpress
- name: Download wordpress
  get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"
  when: not tar_wordpress.stat.exists

# Comprobar si wordpress está instalado
- name: Check wordpress is instaled
  stat:
          path: "/var/www/html/wordpress"
  register: wordpress_files

# Descomprimir archivo de wordpress
- name: Unzip wordpress
  unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/html"
        remote_src: yes
        owner: www-data
        group: www-data
        mode: '0755'
  when: not wordpress_files.stat.exists
  register: installation

# Estabalcer configuración wp-config.php
- name: Set config
  template:
        src: files/Debian/wp-config.php
        dest: /var/www/html/wordpress/wp-config.php
        owner: www-data
        group: www-data
        mode: '0755'
  when: installation.changed

# Estabecer conf
- name: Import file wordpress.conf(proxy)
  template:
          src: files/Debian/000-default.conf.j2
          dest: /etc/apache2/sites-available/000-default.conf
          owner: root
          group: root
          mode: '0644'
  when: installation.changed

# Reiniciar servicio Apache Web Server
- name: Restart apachee Web Server
  become: yes
  service:
        name: apache2
        state: restarted
  when: installation.changed

# Reiniciar servidor
- name: Reboot server
  reboot:
        reboot_timeout: 30
        post_reboot_delay: 30
